version: "3.9"
services:
  postgres:
    image: postgres:12-alpine
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: blog
    expose:
      - "5432"

  blog:
    build:
        context: ./blog
        dockerfile: Dockerfile
    depends_on:
      - postgres
    expose:
      - "3333"

  daily:
    build:
        context: ./daily
        dockerfile: Dockerfile
    expose:
      - "2222"

  registerlogin:
    build:
        context: ./registerlogin
        dockerfile: Dockerfile
    depends_on:
      - blog
      - daily
    ports:
      - "8080:1111"